---
title: "Analisis factorial confirmatorio"
output: html_Analisis_Factorial_Confirmatorio
---


Para correr una linea, utilizar *Ctrl+Shift+Enter*

Para insertar una nueva linea de codigo, utilizar *Ctrl+Alt+I*


```{r}
##Iniciar función paquetes
ipak <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg)) 
    install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE)
}
```


```{r}
##Asignar paquetes
packages <- c("parameters","apa","haven","ggplot2","ggpubr","gridExtra","apaTables", "reshape", "GPArotation", "mvtnorm", "psych", "psychometric", "lavaan", "nFactors", "semPlot", "lavaan", "MVN", "semTools")

```


```{r}
##Abrir paquetes
ipak(packages)
```


```{r}
##Abrir archivo de trabajo
Estructura11
```


```{r}
##Asignar el modelo de dos factores
DosFactores<- 'Factor1 =~ Q17_2 + Q17_3 + Q17_4 + Q17_1 + Q17_9 + Q17_7
Factor2 =~ Q17_6 + Q17_5 + Q17_11 + Q17_10'

```


```{r}
##Analisis factorial confirmatorio AFC
AFC_E1_2F<- cfa(DosFactores,orthogonal=FALSE, data=Estructura11, estimator="WLSMV",ordered =names(Estructura11))
```


```{r}
##Resumen del modelo
summary(AFC_E1_2F, fit.measures=TRUE)
```


```{r}
##Ajuste del modelo
fitMeasures(AFC_E1_2F)
```


```{r}
##Ver modelo
semPaths(AFC_E1_2F, intercepts = FALSE,edge.label.cex=1.5, optimizeLatRes = TRUE, groups = "lat",pastel = TRUE, exoVar = FALSE, sizeInt=5,edge.color ="black",esize = 6, label.prop=2,sizeLat = 6,"std", layout="circle2")

```

```{r}
#Guardar la syntaxis del trabajo

```

Guardar la syntaxis del trabajo
Utilizar *Ctrl+Shift+K* sobre un Chunk (linea de trabajo)

